### ISSUE TITLE
由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by lotusxhaofda001** [testerzhang/jd_pc_auto_practise#2]
Traceback (most recent call last):
  File "S:\01_Python\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "S:\01_Python\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "S:\01_Python\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by testerzhang** [comment]
启动appium server那个界面服务了吗？
